# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=100)),
                ('answer1', models.CharField(max_length=20)),
                ('answer2', models.CharField(max_length=20)),
                ('answer3', models.CharField(max_length=20)),
                ('answer4', models.CharField(max_length=20)),
                ('rightAnswer', models.IntegerField(choices=[('1', models.CharField(max_length=20)), ('2', models.CharField(max_length=20)), ('3', models.CharField(max_length=20)), ('4', models.CharField(max_length=20))])),
                ('rayon', models.FloatField(default=2)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Position')),
            ],
        ),
    ]
